/**
 * Standard lists for doctor specialization and department dropdowns.
 * Used in DoctorForm, DoctorList filters, and AdminDoctorManagement.
 */

export const SPECIALIZATIONS = [
  'Cardiology',
  'Pediatrics',
  'Orthopedics',
  'Dermatology',
  'Neurology',
  'Gynecology',
  'Oncology',
  'Psychiatry',
  'Emergency Medicine',
  'General Medicine',
  'Internal Medicine',
  'Surgery',
  'Radiology',
  'Anesthesiology',
  'Ophthalmology',
  'ENT (Ear, Nose & Throat)',
  'Urology',
  'Gastroenterology',
  'Pulmonology',
  'Nephrology',
  'Rheumatology',
  'Endocrinology',
  'Infectious Disease',
  'Pathology',
  'Physical Medicine & Rehabilitation',
  'Family Medicine',
  'Other',
];

export const DEPARTMENTS = [
  'Cardiology',
  'Pediatrics',
  'Orthopedics',
  'Dermatology',
  'Neurology',
  'Gynecology',
  'Oncology',
  'Psychiatry',
  'Emergency',
  'General Medicine',
  'Internal Medicine',
  'Surgery',
  'Radiology',
  'Anesthesiology',
  'Ophthalmology',
  'ENT',
  'Urology',
  'Gastroenterology',
  'Pulmonology',
  'Nephrology',
  'Rheumatology',
  'Endocrinology',
  'Infectious Disease',
  'Pathology',
  'Rehabilitation',
  'Family Medicine',
  'Other',
];
